# Generated by Django 5.2.4 on 2025-07-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_leaderboard_quizquestion_delete_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(max_length=255),
        ),
    ]
